apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-with-labels
  labels:
    team: frontend
    version: 1.0.0
    environment: testing
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80