apiVersion: batch/v1
kind: Job
metadata:
  name: job-consolelog
spec:
  completions: 5
  parallelism: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: job-consolelog-container
          image: my-job-image:latest
          imagePullPolicy: Never
