apiVersion: batch/v1
kind: CronJob
metadata:
  name: job-consolelog
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: job-consolelog-container
              image: my-job-image:latest
